# Generated by Django 5.1.5 on 2025-05-04 16:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniTwitter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='seguindo',
            field=models.ManyToManyField(blank=True, related_name='seguidores', to=settings.AUTH_USER_MODEL),
        ),
    ]
